// ─── Catálogo de rubros (verticales) ────────────────────────────────────────
// Cada rubro define el vocabulario, emoji, catálogo inicial y si aplica urgencia
// o RUT. La clínica elige su rubro (variable RUBRO) y el bot adapta todos los textos.
// El "ajuste fino" se hace con variables RUBRO_* que sobreescriben campos puntuales.

const RUBROS = {
  dental: {
    nombre: "Clínica Dental", emoji: "🦷", profesional: "dentista",
    servicioSing: "tratamiento", servicioPlural: "tratamientos",
    urgencia: true, urgenciaEjemplos: "dolor, inflamación, golpe",
    urgenciaPalabras: "dolor|sangra|sangrado|fractura|inflamaci|absceso|hinchaz|golpe|accidente|me caí|se me rompió",
    pideRut: true,
    ia: "tratamientos dentales (limpieza, ortodoncia, implantes, blanqueamiento, endodoncia, extracciones)",
    servicios: ["Limpieza dental","Revisión general / chequeo","Ortodoncia (brackets o alineadores)","Implante o prótesis dental","Extracción dental","Blanqueamiento dental","Tratamiento de conducto (endodoncia)","Otro / No sé aún"],
  },
  kinesiologia: {
    nombre: "Centro de Kinesiología", emoji: "💪", profesional: "kinesiólogo/a",
    servicioSing: "sesión", servicioPlural: "sesiones",
    urgencia: true, urgenciaEjemplos: "dolor agudo, lesión reciente",
    urgenciaPalabras: "dolor|lesión|lesion|esguince|desgarro|no puedo mover|no puedo caminar|accidente",
    pideRut: true,
    ia: "kinesiología y rehabilitación física (terapia deportiva, post-operatorio, dolor lumbar, cervical)",
    servicios: ["Evaluación kinésica","Sesión de rehabilitación","Terapia deportiva","Kinesioterapia respiratoria","Masoterapia","Punción seca","Otro / No sé aún"],
  },
  quiropractica: {
    nombre: "Centro Quiropráctico", emoji: "🧘", profesional: "quiropráctico/a",
    servicioSing: "sesión", servicioPlural: "sesiones",
    urgencia: true, urgenciaEjemplos: "dolor agudo, lumbago",
    urgenciaPalabras: "dolor|lumbago|cervical|ciática|ciatica|no puedo mover|contractura",
    pideRut: true,
    ia: "quiropráctica y ajustes de columna (dolor de espalda, cervical, lumbago, postura)",
    servicios: ["Evaluación postural","Ajuste quiropráctico","Sesión de seguimiento","Terapia de columna","Otro / No sé aún"],
  },
  psicologia: {
    nombre: "Consulta Psicológica", emoji: "🧠", profesional: "psicólogo/a",
    servicioSing: "sesión", servicioPlural: "sesiones",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: true,
    ia: "atención psicológica (terapia individual, de pareja, infantil, ansiedad, depresión)",
    servicios: ["Primera consulta / evaluación","Sesión de terapia individual","Terapia de pareja","Terapia infantil / adolescente","Otro / No sé aún"],
  },
  nutricion: {
    nombre: "Consulta Nutricional", emoji: "🥗", profesional: "nutricionista",
    servicioSing: "consulta", servicioPlural: "consultas",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: true,
    ia: "nutrición y alimentación (control de peso, planes alimenticios, nutrición deportiva, seguimiento)",
    servicios: ["Primera consulta nutricional","Control / seguimiento","Plan alimentario","Nutrición deportiva","Otro / No sé aún"],
  },
  medicina: {
    nombre: "Centro Médico", emoji: "🩺", profesional: "médico/a",
    servicioSing: "consulta", servicioPlural: "consultas",
    urgencia: true, urgenciaEjemplos: "fiebre alta, dolor intenso",
    urgenciaPalabras: "dolor|fiebre|emergencia|urgente|sangra|dificultad para respirar|desmayo|accidente",
    pideRut: true,
    ia: "medicina general y consultas médicas (controles, exámenes, licencias, atención preventiva)",
    servicios: ["Consulta general","Control / seguimiento","Chequeo preventivo","Certificado / licencia","Otro / No sé aún"],
  },
  oftalmologia: {
    nombre: "Centro Oftalmológico", emoji: "👁", profesional: "oftalmólogo/a",
    servicioSing: "atención", servicioPlural: "atenciones",
    urgencia: true, urgenciaEjemplos: "dolor ocular, pérdida de visión",
    urgenciaPalabras: "dolor|no veo|pérdida de visión|perdida de vision|golpe en el ojo|algo en el ojo|urgente",
    pideRut: true,
    ia: "oftalmología (control visual, cirugía láser, adaptación de lentes, exámenes de la vista)",
    servicios: ["Control visual","Examen de la vista","Adaptación de lentes","Evaluación cirugía láser","Otro / No sé aún"],
  },
  podologia: {
    nombre: "Centro de Podología", emoji: "🦶", profesional: "podólogo/a",
    servicioSing: "atención", servicioPlural: "atenciones",
    urgencia: true, urgenciaEjemplos: "uña encarnada, dolor al caminar",
    urgenciaPalabras: "dolor|uña encarnada|una encarnada|infección|infeccion|no puedo caminar|herida",
    pideRut: true,
    ia: "podología (uñas encarnadas, callosidades, pie diabético, podología clínica y deportiva)",
    servicios: ["Podología general","Uña encarnada","Pie diabético","Podología deportiva","Otro / No sé aún"],
  },
  estetica: {
    nombre: "Centro de Estética", emoji: "💅", profesional: "especialista",
    servicioSing: "tratamiento", servicioPlural: "tratamientos",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: false,
    ia: "estética y dermatología (limpieza facial, depilación, tratamientos corporales, rejuvenecimiento)",
    servicios: ["Limpieza facial","Depilación","Tratamiento corporal","Tratamiento facial anti-edad","Otro / No sé aún"],
  },
  masajes: {
    nombre: "Centro de Masajes & Spa", emoji: "💆", profesional: "terapeuta",
    servicioSing: "sesión", servicioPlural: "sesiones",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: false,
    ia: "masoterapia y spa (masaje relajante, descontracturante, drenaje linfático, piedras calientes)",
    servicios: ["Masaje relajante","Masaje descontracturante","Drenaje linfático","Piedras calientes","Otro / No sé aún"],
  },
  peluqueria: {
    nombre: "Peluquería & Barbería", emoji: "💇", profesional: "estilista",
    servicioSing: "servicio", servicioPlural: "servicios",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: false,
    ia: "peluquería y barbería (corte, color, peinado, tratamientos capilares, barba)",
    servicios: ["Corte de pelo","Color / tintura","Peinado","Tratamiento capilar","Corte de barba","Otro / No sé aún"],
  },
  manicure: {
    nombre: "Centro de Manicure", emoji: "💅", profesional: "manicurista",
    servicioSing: "servicio", servicioPlural: "servicios",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: false,
    ia: "manicure y pedicure (esmaltado permanente, uñas acrílicas, kapping, pedicure)",
    servicios: ["Manicure","Pedicure","Esmaltado permanente","Uñas acrílicas / gel","Otro / No sé aún"],
  },
  veterinaria: {
    nombre: "Clínica Veterinaria", emoji: "🐶", profesional: "veterinario/a",
    servicioSing: "atención", servicioPlural: "atenciones",
    urgencia: true, urgenciaEjemplos: "mi mascota está grave, no come",
    urgenciaPalabras: "grave|no come|no respira|sangra|convulsión|convulsion|atropell|envenen|emergencia|urgente",
    pideRut: false,
    ia: "veterinaria (consultas, vacunas, controles, cirugías, urgencias de mascotas)",
    servicios: ["Consulta general","Vacunación","Control / desparasitación","Peluquería canina","Otro / No sé aún"],
  },
  consultoria: {
    nombre: "Servicios Profesionales", emoji: "💼", profesional: "profesional",
    servicioSing: "servicio", servicioPlural: "servicios",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: false,
    ia: "servicios profesionales y consultoría (asesorías, reuniones, evaluaciones)",
    servicios: ["Primera reunión / evaluación","Asesoría","Seguimiento","Otro / No sé aún"],
  },
  tatuajes: {
    nombre: "Estudio de Tatuajes", emoji: "🎨", profesional: "tatuador/a",
    servicioSing: "servicio", servicioPlural: "servicios",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: false,
    ia: "estudio de tatuajes y piercing (diseño, sesiones de tatuaje, retoques, piercing)",
    servicios: ["Consulta / cotización de diseño","Sesión de tatuaje","Retoque","Piercing","Otro / No sé aún"],
  },
  otro: {
    nombre: "Centro de Atención", emoji: "📅", profesional: "profesional",
    servicioSing: "servicio", servicioPlural: "servicios",
    urgencia: false, urgenciaEjemplos: "",
    urgenciaPalabras: "",
    pideRut: false,
    ia: "los servicios que ofrece el negocio",
    servicios: ["Servicio 1","Servicio 2","Otro / No sé aún"],
  },
};

// Lista para selectores (id, nombre, emoji) en el orden deseado
const RUBROS_LISTA = Object.entries(RUBROS).map(([id, r]) => ({ id, nombre: r.nombre, emoji: r.emoji }));

module.exports = { RUBROS, RUBROS_LISTA };
